### ISSUE TITLE
Wayland Rendering Issues

### ISSUE THREAD

**Issue by jhyvictory** [cycfi/elements#383] opened 2024-03-23 01:58 UTC
for example I run the Rain example:
./Rain
then error happen:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: SkSurface::MakeRenderTarget returned null

sys: Ubuntu 22.04.4 LTS

**Comment by djowel** [comment] 2024-03-23 01:59
Are you using a Virtual Machine?

**Comment by jhyvictory** [comment] 2024-03-23 13:13
Not a virtual machine. my cpu is AMD® Ryzen 5 5600g with radeon graphics × 12, no independent gpu.

**Comment by djowel** [comment] 2024-03-23 14:10
Try updating the graphics driver. This is a Skia issue. If that does not work, I have an MCVE that you can try (skia only, no elements). If that exhibits problems, the next thing is to ask the Skia forum.

Meanwhile, you can use the Cairo branch: `cairo_2024_dev` or `cairo_2024`

**Comment by jhyvictory** [comment] 2024-03-24 00:09
I have checked to the cairo_2024 branch, but when I use cmake, an cmake error occured even though I have pull all the submodules by `git submodule update --init --recursive`
Is there anything wrong with the cmake file?
`
-- Checking for module 'libwebp'
--   No package 'libwebp' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  lib/CMakeLists.txt:274 (pkg_check_modules)
`

**Comment by jhyvictory** [comment] 2024-03-24 00:10
BTW: My graphics driver is up-to-date.

**Comment by djowel** [comment] 2024-03-24 00:23
> I have checked to the cairo_2024 branch, but when I use cmake, an cmake error occured even though I have pull all the submodules by `git submodule update --init --recursive` Is there anything wrong with the cmake file? `-- Checking for module 'libwebp' -- No package 'libwebp' found CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message): A required package was not found Call Stack (most recent call first): /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal) lib/CMakeLists.txt:274 (pkg_check_modules)`

Yes, libwebp is a dependency now:

```
sudo apt-get install libwebp-dev
```

**Comment by jhyvictory** [comment] 2024-03-24 00:51
It works!
Thanks!

**Comment by djowel** [comment] 2024-03-24 00:59
> It works! Thanks!

Good to know. 

I'm trying to fix the Skia problem though. I would liike to keep this issue open. 

Would you care to try some things if I have some workarounds we can try? The problem is that the issue you reported happens only on some setups. I, personally, am not able to reporduce it.

**Comment by jhyvictory** [comment] 2024-03-24 09:10
Okay, if you want me to try something new, just let me know.

**Comment by djowel** [comment] 2024-03-25 02:57
> Okay, if you want me to try something new, just let me know.

OK, I believe it is fixed now, and merged in the `master` and `develop` branches. Can you please try? Thanks!

**Comment by jhyvictory** [comment] 2024-03-25 23:49
I changed to the master branch and removed the libwebp-dev to make the situation same with the last time. Everyting is ok and I can run all the examples. But it seems that something is wrong with the repaint mechnism of elements UI. Let me show you with pictures.

**Comment by jhyvictory** [comment] 2024-03-25 23:50
![IMG_20240326_074712.jpg](https://github.com/cycfi/elements/assets/18344919/45e67f8e-4cb1-4bc3-98e7-5c7cfb460d99)

![IMG_20240326_074742.jpg](https://github.com/cycfi/elements/assets/18344919/5bce8e45-8f84-4075-b494-57fc3cb8c96d)

![IMG_20240326_074820.jpg](https://github.com/cycfi/elements/assets/18344919/a10f20c6-4ae8-44dd-9593-8034ab0582ec)

**Comment by jhyvictory** [comment] 2024-03-25 23:54
I must take photos to grasp the phenomenon because if I use a screenshot tool, the interface will become normal.

**Comment by djowel** [comment] 2024-03-26 00:03
OK, I'll need a way to reporduce this. In the meantime, please use the cairo_2024 branch.

**Comment by jhyvictory** [comment] 2024-03-26 00:13
cairo_2024 branch has the same problem for I have tried it last time. Some examples even immediately crashed in Windows when I run them.

**Comment by djowel** [comment] 2024-03-26 00:27
> cairo_2024 branch has the same problem for I have tried it last time. Some examples even immediately crashed in Windows when I run them.

Hmmm... cairo has been very stable for many years now. I'll need more info. Is this on Windows only? Would you care having a more immediate discussion via Discord? https://discord.gg/NJkadSx

**Comment by djowel** [comment] 2024-03-26 00:38
> Some examples even immediately crashed in Windows when I run them.

Could you be more specific? There may be some recent updates that might have caused instabilities. IDK.

It would be great if we can have a more interactive discussion via Discord: https://discord.gg/NJkadSx

**Comment by djowel** [comment] 2024-03-28 15:59
Update: I can confirm that cairo_2024 works well with both Wayland and Xorg on 

1. an Ubuntu 22.04.4 LTS VM with arm64 hosted on MacOS 
2. an Ubuntu 22.04.4 LTS VM running on a Dell i7 (x86-64)

I can also confirm the issues reported here with the current develop and master (Skia backend) under Wayland, but works well on Xorg.

**Comment by djowel** [comment] 2024-03-28 16:00
@jhyvictory Also confirms (in Discord) that cairo_2024 works well with Wayland.

**Comment by djowel** [comment] 2024-03-29 02:04
Fixed now. Confirmed in both wayland and xorg.

**Closed** 2024-03-29 02:07 UTC
