### ISSUE TITLE
Error while running Unix Makefile

### ISSUE THREAD

**Issue by notshriram** [cycfi/elements#296] opened 2022-02-20 16:12 UTC
I am running macOS Monterey 12.2.1 on M1

I ran cmake and made the Unix Makefile as per the Setup & Installation section in the documentation.

When I run the Makefile with the make command, I get the following error:

```
[  1%] Building CXX object lib/CMakeFiles/elements.dir/src/element/button.cpp.o
[  2%] Building CXX object lib/CMakeFiles/elements.dir/src/element/child_window.cpp.o
[  3%] Building CXX object lib/CMakeFiles/elements.dir/src/element/composite.cpp.o
[  4%] Building CXX object lib/CMakeFiles/elements.dir/src/element/dial.cpp.o
[  5%] Building CXX object lib/CMakeFiles/elements.dir/src/element/dynamic_list.cpp.o
[  6%] Building CXX object lib/CMakeFiles/elements.dir/src/element/element.cpp.o
[  8%] Building CXX object lib/CMakeFiles/elements.dir/src/element/floating.cpp.o
[  9%] Building CXX object lib/CMakeFiles/elements.dir/src/element/flow.cpp.o
[ 10%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/button.cpp.o
[ 11%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/check_box.cpp.o
[ 12%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/icon_button.cpp.o
[ 13%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/menu.cpp.o
[ 15%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/radio_button.cpp.o
[ 16%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/tab.cpp.o
[ 17%] Building CXX object lib/CMakeFiles/elements.dir/src/element/gallery/thumbwheel.cpp.o
[ 18%] Building CXX object lib/CMakeFiles/elements.dir/src/element/grid.cpp.o
[ 19%] Building CXX object lib/CMakeFiles/elements.dir/src/element/image.cpp.o
[ 20%] Building CXX object lib/CMakeFiles/elements.dir/src/element/label.cpp.o
[ 22%] Building CXX object lib/CMakeFiles/elements.dir/src/element/layer.cpp.o
[ 23%] Building CXX object lib/CMakeFiles/elements.dir/src/element/menu.cpp.o
[ 24%] Building CXX object lib/CMakeFiles/elements.dir/src/element/misc.cpp.o
[ 25%] Building CXX object lib/CMakeFiles/elements.dir/src/element/popup.cpp.o
[ 26%] Building CXX object lib/CMakeFiles/elements.dir/src/element/port.cpp.o
[ 27%] Building CXX object lib/CMakeFiles/elements.dir/src/element/progress_bar.cpp.o
[ 29%] Building CXX object lib/CMakeFiles/elements.dir/src/element/proxy.cpp.o
[ 30%] Building CXX object lib/CMakeFiles/elements.dir/src/element/slider.cpp.o
[ 31%] Building CXX object lib/CMakeFiles/elements.dir/src/element/text.cpp.o
[ 32%] Building CXX object lib/CMakeFiles/elements.dir/src/element/thumbwheel.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/elements.dir/src/element/tile.cpp.o
[ 34%] Building CXX object lib/CMakeFiles/elements.dir/src/element/tooltip.cpp.o
[ 36%] Building CXX object lib/CMakeFiles/elements.dir/src/support/canvas.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/elements.dir/src/support/draw_utils.cpp.o
[ 38%] Building CXX object lib/CMakeFiles/elements.dir/src/support/font.cpp.o
[ 39%] Building CXX object lib/CMakeFiles/elements.dir/src/support/glyphs.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/elements.dir/src/support/pixmap.cpp.o
[ 41%] Building CXX object lib/CMakeFiles/elements.dir/src/support/receiver.cpp.o
[ 43%] Building CXX object lib/CMakeFiles/elements.dir/src/support/rect.cpp.o
[ 44%] Building CXX object lib/CMakeFiles/elements.dir/src/support/text_utils.cpp.o
[ 45%] Building CXX object lib/CMakeFiles/elements.dir/src/support/resource_paths.cpp.o
[ 46%] Building CXX object lib/CMakeFiles/elements.dir/src/support/theme.cpp.o
[ 47%] Building CXX object lib/CMakeFiles/elements.dir/src/view.cpp.o
[ 48%] Building CXX object lib/CMakeFiles/elements.dir/host/macos/app.mm.o
/Users/username/Dev/CppProjects/elements/lib/host/macos/app.mm:24:7: error: use of undeclared identifier '_menubar'; did you mean 'menubar_'?
      _menubar = (__bridge void*) menubar_;
      ^~~~~~~~
      menubar_
/Users/username/Dev/CppProjects/elements/lib/host/macos/app.mm:23:10: note: 'menubar_' declared here
      id menubar_ = [NSMenu new];
         ^
/Users/username/Dev/CppProjects/elements/lib/host/macos/app.mm:24:18: error: assigning to 'id' from incompatible type 'void *'
      _menubar = (__bridge void*) menubar_;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/username/Dev/CppProjects/elements/lib/host/macos/app.mm:6:
/Users/username/Dev/CppProjects/elements/lib/include/elements/app.hpp:40:23: warning: private field '_app' is not used [-Wunused-private-field]
      GtkApplication* _app;
                      ^
1 warning and 2 errors generated.
make[2]: *** [lib/CMakeFiles/elements.dir/host/macos/app.mm.o] Error 1
make[1]: *** [lib/CMakeFiles/elements.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by djowel** [comment] 2022-02-21 00:10
Hmmm... Unix Makefile on macOS? I suppose you did cmake -GXcode ../ ? Can you try building with xcode instead?

**Comment by ordisbold** [comment] 2022-02-21 00:51
I don't think that's the issue. I just built the master branch like this:

mkdir build
cd build
cmake ../
make

And it built fine. 
<img width="831" alt="Screen Shot 2022-02-21 at 07 49 00" src="https://user-images.githubusercontent.com/21118257/154872499-71c9d541-d96e-4145-b10e-a914b9dbe867.png">

Maybe the used compiler (version) is the problem. 

I used:

Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ordisbold** [comment] 2022-02-21 01:12
It's unrelated to the compiler. 

ELEMENTS_HOST_UI_LIBRARY_GTK is defined and ELEMENTS_HOST_UI_LIBRARY_COCOA is not. Yet it's trying to build build the Objective C files because they depend on "Apple" variable in CMakeLists. 

Looks like the OP tries to build against GTK on MacOS.

**Comment by ordisbold** [comment] 2022-02-21 01:25
Reproducible:

<img width="1182" alt="Screen Shot 2022-02-21 at 08 25 07" src="https://user-images.githubusercontent.com/21118257/154874468-62093516-6145-437d-b441-c35eaacec12e.png">

**Comment by djowel** [comment] 2022-02-21 01:44
I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?

**Comment by bold84** [comment] 2022-02-21 01:47
> I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?

It's not a bug. The OP should just not configure his/her build like so:

cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk

Or do you want GTK+3 support for MacOS?

**Comment by djowel** [comment] 2022-02-21 01:54
> > I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?
> 
> It's not a bug. The OP should just **not** configure his/her build like so:
> 
> cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk
> 
> Or do you want GTK+3 support for MacOS?

I suppose so... I don't need it and haven't tried it, but I suppose the OP needs it? Allowing that makes the GTK3 host available on all three supported platforms.

**Comment by bold84** [comment] 2022-02-21 02:00
Alright. I'll do it after I'm back from the gym. 🏋️

Btw., I was considering to see if Skia (additionally)  as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.

**Comment by djowel** [comment] 2022-02-21 02:01
> Btw., I was considering to see if Skia (additionally) as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.

Have a look at the `artist_port` branch :-)

**Comment by notshriram** [comment] 2022-02-21 02:02
> > I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?
> 
> It's not a bug. The OP should just **not** configure his/her build like so:
> 
> cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk
> 
> Or do you want GTK+3 support for MacOS?

Do you mean I need to use `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=cocoa`?

I used `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk` previously which threw the above error

**Comment by djowel** [comment] 2022-02-21 02:03
> > Btw., I was considering to see if Skia (additionally) as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.
> 
> Have a look at the `artist_port` branch :-)

That said, what I really wish is backporting the cairo target to the `artist` library used in the `artist_port ` branch. I already did some work on it some time ago. But there's still work to do.

**Comment by bold84** [comment] 2022-02-21 02:04
> > > I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?
> > 
> > 
> > It's not a bug. The OP should just **not** configure his/her build like so:
> > cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk
> > Or do you want GTK+3 support for MacOS?
> 
> Do you mean I need to use `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=cocoa`?
> 
> I used `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk` previously which threw the above error

Just follow the setup guide and you should not experience any problems. If you change something, expect results to change as well.

Nontheless:

**Comment by djowel** [comment] 2022-02-21 02:07
> > > I see. OK, it seems you have an understanding of the issue. Would you care to find a fix and do a PR?
> > 
> > 
> > It's not a bug. The OP should just **not** configure his/her build like so:
> > cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk
> > Or do you want GTK+3 support for MacOS?
> 
> Do you mean I need to use `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=cocoa`?
> 
> I used `cmake ../ -DELEMENTS_HOST_UI_LIBRARY=gtk` previously which threw the above error

Out of curiosity, why do you want to use GTK on MacOS?

**Comment by notshriram** [comment] 2022-02-21 02:18
> Out of curiosity, why do you want to use GTK on MacOS?

No particular reason, really.

I just saw there were instructions for making unix makefiles for windows and linux but not for macOS and I figured macOS supports gtk too so I thought it should just work. Moreover xcode is a bit too bulky for my liking.

Thank you for your help :)

**Comment by bold84** [comment] 2022-02-21 02:28
@

> > Out of curiosity, why do you want to use GTK on MacOS?
> 
> No particular reason, really.
> 
> I just saw there were instructions for making unix makefiles for windows and linux but not for macOS and I figured macOS supports gtk too so I thought it should just work. Moreover xcode is a bit too bulky for my liking.
> 
> and just running `cmake -G "Unix Makefiles" ` without any additions, threw this error
> 
> ```
> [ 54%] Building CXX object examples/empty/CMakeFiles/EmptyStarter.dir/main.cpp.o
> make[2]: *** No rule to make target `/usr/local/opt/cairo/lib/libcairo.a', needed by `examples/empty/EmptyStarter.app/Contents/MacOS/EmptyStarter'.  Stop.
> make[1]: *** [examples/empty/CMakeFiles/EmptyStarter.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> Thank you for your help :)

mkdir build && cd build && cmake.. /

**Comment by bold84** [comment] 2022-02-21 02:35
@djowel it might be a good idea to merge that PR to master. I assume that the OP tried to  build against GTK because he ran into the problem the PR solves.

**Comment by djowel** [comment] 2022-02-21 03:03
> @djowel it might be a good idea to merge that PR to master. I assume that the OP tried to build against GTK because he ran into the problem the PR solves.

Done.

**Comment by bold84** [comment] 2022-02-21 07:07
I can get it to build and link against GTK3 on Mac, but only some of the example apps work, most crash. 

Looks like it takes more time to figure out why. I don't think that it's worth the effort, since @notshriram did not have a particular reason to choose GTK3 to begin with.

**Comment by djowel** [comment] 2022-02-21 07:09
> I can get it to build and link against GTK3 on Mac, but only some of the example apps work, most crash.
> 
> Looks like it takes more time to figure out why. I don't think that it's worth the effort, since @notshriram did not have a particular reason to choose GTK3 to begin with.

Agreed. Let's make it an error then.

**Comment by bold84** [comment] 2022-02-21 08:14
> > > Btw., I was considering to see if Skia (additionally) as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.
> > 
> > 
> > Have a look at the `artist_port` branch :-)
> 
> That said, what I really wish is backporting the cairo target to the `artist` library used in the `artist_port ` branch. I already did some work on it some time ago. But there's still work to do.

I had a look at it but I couldn't immediately build it because it downloads prebuilt binaries of the artist library for x86_64 for mac and Linux but I have ARM everywhere 😂

But I have the impression that this is exactly what I had on my mind 😁

**Comment by djowel** [comment] 2022-02-21 08:21
> > > > Btw., I was considering to see if Skia (additionally) as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.
> > > 
> > > 
> > > Have a look at the `artist_port` branch :-)
> > 
> > 
> > That said, what I really wish is backporting the cairo target to the `artist` library used in the `artist_port ` branch. I already did some work on it some time ago. But there's still work to do.
> 
> I had a look at it but I couldn't immediately build it because it downloads prebuilt binaries of the artist library for x86_64 for mac and Linux but I have ARM everywhere 😂
> 
> But I have the impression that this is exactly what I had on my mind 😁

Ah of course! It would be great to have support for ARM. I'm still on the old intel.

**Comment by bold84** [comment] 2022-02-21 08:33
> > > > > Btw., I was considering to see if Skia (additionally) as an alternative to cairo would be of interest. I know that Flutter uses Skia under the hood and Skia works on mobile and the web. They might pave the way for these two platforms.
> > > > 
> > > > 
> > > > Have a look at the `artist_port` branch :-)
> > > 
> > > 
> > > That said, what I really wish is backporting the cairo target to the `artist` library used in the `artist_port ` branch. I already did some work on it some time ago. But there's still work to do.
> > 
> > 
> > I had a look at it but I couldn't immediately build it because it downloads prebuilt binaries of the artist library for x86_64 for mac and Linux but I have ARM everywhere 😂
> > But I have the impression that this is exactly what I had on my mind 😁
> 
> Ah of course! It would be great to have support for ARM. I'm still on the old intel.

Before I start assuming what needs to be done after I got it built... I better ask;
What exactly do you want to be done? Do you want elements to be part of artist, artist to be part of elements? Or keep them separated?
Is there a document with the todos?

What I imagine is to get elements to built for Android and IOS as well, possibly even Webassembly. 
Afterwards implement mobile specific UI elements, touch support, ...

**Comment by djowel** [comment] 2022-02-21 08:35
Good questions! I'll get back to you later...

**Comment by djowel** [comment] 2022-02-21 08:36
But one thing clear is that I want artist to be separated from elements. It is useful as it is.

**Comment by djowel** [comment] 2022-02-22 00:12
OK, I'm going to close this now. @notshriram feel free to re-open if you are still having issues.

**Closed by djowel** 2022-02-22 00:12 UTC
