### ISSUE TITLE
text_edit example seems to crash if backspace and type fast

### ISSUE THREAD

**Issue by dirkarnez** [cycfi/elements#206] opened 2020-08-17 08:08 UTC
Test
![image](https://user-images.githubusercontent.com/26408605/90372810-91491b80-e0a3-11ea-95cc-8fd13f2dc5b9.png)

Not sure if it is runtime dependency problem or not, just accidentally crash text_edit example if backspace and type fast at the same time.

**Comment by djowel** [comment] 2020-08-17 08:15
do you have a stack dump? or can you run using debug to see where it crashed?

**Comment by dirkarnez** [comment] 2020-08-20 08:12
Sure

The debugger stops at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include\xstring`
![image](https://user-images.githubusercontent.com/26408605/90733817-a3bf9100-e2ff-11ea-90c6-9ae91e877e05.png)

if continue, the debugger brings me to the `elements\lib\src\support\glyphs.cpp`, line 282
![image](https://user-images.githubusercontent.com/26408605/90734753-e3867880-e2ff-11ea-9a05-0fa6df28c099.png)

Hopefully, it helps! Thank you!

**Comment by djowel** [comment] 2020-08-20 09:58
I can't repro. Could you clarify what you mean by "backspace and type fast at the same time." So I tried typing random text with my left hand and pressing delete many times with my right. I can't get it to crash. Or do you mean just pressing delete fast many times? But I can't get it to crash that way too. I tried MacOS. I'll try Windows tomorrow.

**Comment by redtide** [comment] 2020-08-20 10:07
Might be a Windows only issue, I tried it on Linux without tragic consequences.

**Comment by Xeverous** [comment] 2020-08-20 16:25
@dirkarnez Tried on Windows, does not repoduce for me. I use MinGW-w64, so the runtime and cairo builds are different.

**Comment by dirkarnez** [comment] 2020-08-20 16:34
Sorry for my bad English.

I get the crash when I randomly double mouse click random part of the text area (sometimes the cursor selects some text, sometimes the cursor just gets relocated), and at the same time I press backspaces or just type randomly. It takes about 10 to 30 seconds to crash doing these non-stop.

Do you want my compiled exe to try out? Really not sure if I compiled it correctly.

Thank you!

**Comment by dirkarnez** [comment] 2020-08-20 16:36
Mine is a cmake generated VS 2019 project

**Comment by Xeverous** [comment] 2020-08-20 16:57
I don't have your toolchain so even if I had the executable that reproduces the crash, it would still give me no advantages in fixing the bug.

**Comment by redtide** [comment] 2020-08-20 17:23
OK, now I have [something](https://pastebin.com/RHRXsVUx) too.

**Comment by Xeverous** [comment] 2020-08-20 17:52
Chinese font examples? Perhaps this is a regression caused by recent commit?

**Comment by redtide** [comment] 2020-08-20 18:35
> Chinese font examples? Perhaps this is a regression caused by recent commit?

I tried with a build from previous commit 7d40386 and I wasn't able to make it crash, so it seems so...

**Comment by dirkarnez** [comment] 2020-08-21 04:10
> I don't have your toolchain so even if I had the executable that reproduces the crash, it would still give me no advantages in fixing the bug.

I see...

**Comment by dirkarnez** [comment] 2020-08-21 04:11
> examples

I just typed English alphabets and backspaces

**Comment by dirkarnez** [comment] 2020-08-21 04:11
> Chinese font examples? Perhaps this is a regression caused by recent commit?

I just typed English alphabets and backspaces

**Comment by dirkarnez** [comment] 2020-08-21 06:57
![image](https://user-images.githubusercontent.com/26408605/90861610-99180100-e3be-11ea-94c2-fb1faa2bfedb.png)

It is the call stack

**Comment by dirkarnez** [comment] 2020-08-24 04:06
![image](https://user-images.githubusercontent.com/26408605/91002742-1ed7be80-e602-11ea-85c6-b77feb6362b1.png)

If revert correctly, it seems to be the same

**Comment by djowel** [comment] 2020-08-24 05:28
OK, I'll try to repro asap.

**Comment by djowel** [comment] 2020-08-24 06:13
> OK, I'll try to repro asap.

I can't repro on Windows VS2019 :-(

I tried what you said: "randomly double mouse click random part of the text area (sometimes the cursor selects some text, sometimes the cursor just gets relocated), and at the same time I press backspaces or just type randomly."

I'll try to add some failsafe in the code, based on your errors and I'll have you try it again.

**Comment by djowel** [comment] 2020-08-24 06:43
OK, I think I got it. _select_start can actually be greater than _select_end. So this is indeed a bug. @dirkarnez, please verify the fix in develop branch.

**Comment by dirkarnez** [comment] 2020-08-24 07:12
Thanks @djowel, just retried with develop branch, the crash now happens at elements\lib\src\support\glyphs.cpp
![image](https://user-images.githubusercontent.com/26408605/91013639-8ef23e80-e61a-11ea-9f44-07d61894e50c.png)

Thank you!

**Comment by djowel** [comment] 2020-08-24 08:28
Hmmm... Do you have the stack trace and the variables at that point?

**Comment by djowel** [comment] 2020-08-24 09:15
> Hmmm... Do you have the stack trace and the variables at that point?
> 
> Edit: I added a branch debug-206 where I reverted the commit for the chinese fix. Can you try that?
> 
> https://github.com/cycfi/elements/tree/debug-206

Ah Ignore that. Nevermind. I got it to crash!

**Comment by djowel** [comment] 2020-08-24 13:41
OK, please try develop again. Another fix is in. Now I can't get it to crash. Please try.

**Comment by redtide** [comment] 2020-08-24 14:39
On Linux it seems OK.

**Comment by dirkarnez** [comment] 2020-08-25 03:40
Thank you @djowel @redtide just tried on Windows 10, cannot crash now 😍

**Closed** 2020-08-25 03:42 UTC
Labels: bug
